### PR TITLE
Expose russimp-sys 1.0.1 features

### PR DESCRIPTION
**Pull request by JoeOsborn**
I love the new russimp-sys features, and this patch to russimp bumps the russimp-sys version and exposes those features to users of russimp.

### CODE REVIEW

**Comment by jkvargas** [comment]
thanks for your work bro.
can you please raise the version for russimp as well?
1.0.2 will do :)

**Comment by JoeOsborn** [comment]
Sure, I’ll take a look Monday! Should there be any documentation changes, e.g. a link to the sys crate’s readme or a description of the features?

Also, is it confusing for russimp 1.0.2 to depend on -sys 1.0.1?  In other words should the versions match or is it not important?

**Comment by jkvargas** [comment]
version match is not important, sometimes we do update russimp-sys without going for a new version with russimp.

I would say that having the features description in russimp would be better than a link.

**Comment by JoeOsborn** [comment]
Thanks! My hope is that this new feature also fixes docs.rs for russimp, but I guess we’ll see!

**Pull request merged**
