### PR TITLE
Add ability to load scenes with custom properties

### PR DESCRIPTION
**Pull request by cmilatinov**
- Added a `PropertyStore` struct to hold Assimp properties
- Added corresponding `from_*_with_props` functions to `Scene` to load scenes with a property store
- Use match statements in Scene loader functions

Example scene loading code
```Rust
let props: PropertyStore = [(
    AI_CONFIG_IMPORT_FBX_PRESERVE_PIVOTS as &[u8],
    Property::Integer(0),
)]
    .into_iter()
    .into();
let scene = Scene::from_file_with_props(
    path.to_str().unwrap(),
    vec![
        PostProcess::Triangulate,
        PostProcess::GenerateSmoothNormals,
        PostProcess::FlipUVs,
        PostProcess::FlipWindingOrder,
        PostProcess::JoinIdenticalVertices,
    ],
    &props,
)?;
```

### CODE REVIEW

**Comment by jkvargas** [comment]
Hey mate, thanks for your contribution,
I would like to ask you somethings before merging your work.

* Raise the version to 3.2.0
* Add to the changelog your new feature, would be cool if you can add an example.
* I don't see tests on your changes. Would you mind to add a test to validate the features you're exposing to the end user?

**Comment by cmilatinov** [comment]
Hey, 

Yessir, no problem I will go through the checklist ASAP and update the PR.

Cheers

**Comment by cmilatinov** [comment]
Hey @jkvargas,

I've made the changes you requested, just requesting a final review. 

I added an example usage for props in the examples folder :)

Also, I'm a windows user atm, so I hope running the tests with `--features prebuilt` is the correct thing to do

PS: Very cool rust package, I'm glad to be able to contribute!

Have a nice day!

**Comment by jkvargas** [comment]
Thanks for the additions, man.
There are some tests failing.
With those fixed I believe we are good to go.

**Comment by cmilatinov** [comment]
Yea its a compilation error since the `bindings.rs` file isn't generated for the tests I believe so rust can't find the `AI_*` constants.

```Rust
error[E0432]: unresolved imports `crate::sys::AI_CONFIG_IMPORT_COLLADA_IGNORE_UP_DIRECTION`, `crate::sys::AI_CONFIG_IMPORT_COLLADA_USE_COLLADA_NAMES`, `crate::sys::AI_CONFIG_IMPORT_FBX_PRESERVE_PIVOTS`, `crate::sys::AI_CONFIG_IMPORT_FBX_READ_WEIGHTS`, `crate::sys::AI_CONFIG_PP_OG_EXCLUDE_LIST`, `crate::sys::AI_CONFIG_PP_PTV_ADD_ROOT_TRANSFORMATION`, `crate::sys::AI_CONFIG_PP_PTV_ROOT_TRANSFORMATION`
   --> src/property.rs:110:9
    |
110 |         AI_CONFIG_IMPORT_COLLADA_IGNORE_UP_DIRECTION, AI_CONFIG_IMPORT_COLLADA_USE_COLLADA_NAMES,
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `AI_CONFIG_IMPORT_COLLADA_USE_COLLADA_NAMES` in the root
    |         |
    |         no `AI_CONFIG_IMPORT_COLLADA_IGNORE_UP_DIRECTION` in the root
111 |         AI_CONFIG_IMPORT_FBX_PRESERVE_PIVOTS, AI_CONFIG_IMPORT_FBX_READ_WEIGHTS,
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `AI_CONFIG_IMPORT_FBX_READ_WEIGHTS` in the root
    |         |
    |         no `AI_CONFIG_IMPORT_FBX_PRESERVE_PIVOTS` in the root
112 |         AI_CONFIG_PP_OG_EXCLUDE_LIST, AI_CONFIG_PP_PTV_ADD_ROOT_TRANSFORMATION,
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `AI_CONFIG_PP_PTV_ADD_ROOT_TRANSFORMATION` in the root
    |         |
    |         no `AI_CONFIG_PP_OG_EXCLUDE_LIST` in the root
113 |         AI_CONFIG_PP_PTV_ROOT_TRANSFORMATION,
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `AI_CONFIG_PP_PTV_ROOT_TRANSFORMATION` in the root

For more information about this error, try `rustc --explain E0432`.
error: could not compile `russimp` (lib test) due to previous error
```

That's why I ran the tests with `--features prebuilt` locally. Should I just manually copy-paste the constant definitions in the tests?

**Comment by jkvargas** [comment]
I will merge your work and fix this issue.
Thanks brother.

**Pull request merged**
