### PR TITLE
General Improvements

### PR DESCRIPTION
**Pull request by Snowiiii**

### CODE REVIEW

**Comment by jkvargas** [comment]
thank you so much for your contribution Snowiii,
can you please, raise the version of the package to 2.0.6?
Also, if you dont mind, can you please change the Changelog adding a summary of your chages?
Thanks!

**Comment by Snowiiii** [comment]
Done. :D

**Comment by Snowiiii** [comment]
By the way, are you generally familiar with Assimp? If so, could you maybe help me a bit? I'm currently implementing advanced model loading into my game engine, and I could use a bit of help.

**Comment by jkvargas** [comment]
Sure, I will try,
Open a ticket on issues and let discuss there. =)

**Pull request merged**
